# docker-compose.yml
version: '2'

services:
    postgres:
        image: postgres:9.6
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    php:
        build: docker/php7-fpm
        env_file: ./.env
        ports:
            - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        links:
            - postgres

    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - "./var/log/nginx/:/var/log/nginx"
        container_name: symfony4-windock-nginx

    redis:
        image: redis:3.2.10

    node:
        build: docker/node
        volumes:
          - ${SYMFONY_APP_PATH}:/var/www/symfony
        command: bash -c "yarn && yarn dev"